Removing potentially unneeded types...
Because they have huge fragments that can't be executed.

This code eventually blows up with:

  TypeError: result.errors.map is not a function